"""The Eternities data contract, Python side. Frozen at Phase 0; see docs/data-contract.md."""

from .binary import (
    ContractError,
    decode_header,
    decode_sets,
    decode_stars,
    encode_header,
    encode_sets,
    encode_stars,
)
from .encode import (
    EncodedArtefact,
    compute_data_hash,
    encode_artefacts,
    shard_count_for,
    write_dataset,
)
from .enums import (
    BINARY_HEADER_BYTES,
    BINARY_MAGIC,
    BLIND_ETERNITIES_SLUG,
    CONTRACT_VERSION,
    FRAME_RADIUS,
    PIPELINE_VERSION,
    SHARD_SIZE,
    STAR_RECORD_BYTES,
    BinaryKind,
    CardType,
    HueClass,
    PlaneKind,
    SetsSection,
    SizeClass,
    hue_class_for,
    size_class_for,
    type_mask_for,
)
from .images import CARD_BACK_URI, image_uri, page_uri
from .models import (
    Card,
    CardFace,
    Dataset,
    Plane,
    PlaneSetRef,
    Printing,
    SetRecord,
    StarRecord,
)

__all__ = [
    "BINARY_HEADER_BYTES",
    "BINARY_MAGIC",
    "BLIND_ETERNITIES_SLUG",
    "CARD_BACK_URI",
    "CONTRACT_VERSION",
    "FRAME_RADIUS",
    "PIPELINE_VERSION",
    "SHARD_SIZE",
    "STAR_RECORD_BYTES",
    "BinaryKind",
    "Card",
    "CardFace",
    "CardType",
    "ContractError",
    "Dataset",
    "EncodedArtefact",
    "HueClass",
    "Plane",
    "PlaneKind",
    "PlaneSetRef",
    "Printing",
    "SetRecord",
    "SetsSection",
    "SizeClass",
    "StarRecord",
    "compute_data_hash",
    "decode_header",
    "decode_sets",
    "decode_stars",
    "encode_artefacts",
    "encode_header",
    "encode_sets",
    "encode_stars",
    "hue_class_for",
    "image_uri",
    "page_uri",
    "shard_count_for",
    "size_class_for",
    "type_mask_for",
    "write_dataset",
]
